---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/shared/data_bags
  nodes_path: test/shared/nodes

platforms:
  - name: centos-6.6

suites:
  - name: director
    run_list:
      - recipe[bacula-server::director]
    driver:
      network:
        - ["private_network", {ip: "172.16.20.10"}]

  - name: storage
    run_list:
      - recipe[bacula-server::storage]
    driver:
      network:
        - ["private_network", {ip: "172.16.20.12"}]
